### ISSUE TITLE
Using applicationIdSuffix in build flavors causes build exceptions

### ISSUE THREAD

**Issue by andreasmakeable** [gilgoldzweig/Gencycler#1]
I have an app with two flavors, in which one of them has an applicationIdSuffix, and the other one does not. When building to the one without a suffix, everything goes well, but when building to the one with a suffix, it does not work. Must be something related to paths where generated files are saved or something similar.
Please fix this issue

**Comment by gilgoldzweig** [comment]
Please provide me your build file and the error you receive in the gradle console

**Comment by andreasmakeable** [comment]
Here’s my (shortened) build file

apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'com.google.gms.google-services'

apply plugin: 'kotlin-kapt'

apply plugin: 'io.fabric'

android {

    // Signing
    signingConfigs {
        config {
            ...
        }
    }

    // Enable data binding
    dataBinding {
        enabled = true
    }

    // Enable testOptions
    testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
    }

    // Enable Android extensions
    androidExtensions {
        experimental = true
    }

    compileSdkVersion 28
    defaultConfig {
        signingConfig signingConfigs.config

        applicationId "dk.makeable.luxykids"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 8
        versionName "1.0"
        flavorDimensions "default"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    productFlavors {
        luxykids_dev {
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
        }

        luxykids_live {
            versionNameSuffix "-live"
        }
    }
}

dependencies {
    ...
}


The exceptions are related to the fact that my adapter class is extending a class that is not found anywhere, which is why I think the issue has to do with paths to where the generated files are placed. The exceptions are unusable though, I had to run a code inspection to find where something happened.

**Comment by gilgoldzweig** [comment]
You should look at the documentation, there is a [section](https://github.com/gilgoldzweig/Gencycler#miscellaneousoptional) describing your problem 
Look at the resourceFolder part there

If you are using the same layout folder but different productFlavors
You can use the function provided there to give the processor a specific folder to look at

I think if you will use the resource folder section it will solve your problem

**Comment by andreasmakeable** [comment]
I'll look into it and update you if anything changes :)

**Comment by andreasmakeable** [comment]
Update: I inserted the resourses part in the flavors. I do get a deprecated warning

**Comment by andreasmakeable** [comment]
When specifying "main" as my resource folder, I get this error:

> e: error: R.Layout was not found, Are you using multi flavors?
> e: error: Layout not found /Users/andreas/Documents/Makeable/Projekter/Android Projekter/luxykids-android/app/src/main/res/layout/null.xml
> w: warning: The following options were not recognized by any processor: '[kapt.kotlin.generated, resourcesFolder]'

**Comment by gilgoldzweig** [comment]
Set it like this
arguments = [
"rClassPackage": "dk.makeable.luxykids"
]

**Comment by andreasmakeable** [comment]
Thank you, that did the trick. You could make the documentation a little more precise to reflect this issue :)

**Comment by gilgoldzweig** [comment]
Awesome, I'll try to automate this process, and if I can't I will just update the docs

**Comment by andreasmakeable** [comment]
Awesome
