### ISSUE TITLE
Don't cache exceptions

### ISSUE THREAD

**Issue by consp1racy** [gilgoldzweig/Gencycler#7]
Each created exception captures a stacktrace. If you throw a cached exception I'll know exactly where it was instantiated but not where it was thrown, making it useless.

### Current behavior

	private val uiThreadException =
			IllegalThreadStateException("Trying to update the RecyclerView not on main thread")

	open fun add(element: T, position: Int = elements.size) {
		elements.add(position, element)

		if (!updateUi) return
		if (isUiThread()) notifyItemInserted(position) else throw uiThreadException
	}

### Expected behavior

Create a fresh exception. It's already going to fail, just once, no need to worry about performance.

Also, fail fast. First, check function arguments and state, then proceed.

    private fun checkMainThread() {
        if (!isUiThread()) {
            throw IllegalThreadStateException("Trying to update the RecyclerView not on main thread")
        }
    }

    open fun add(element: T, position: Int = elements.size) {
        if (updateUi) {
            checkMainThread()
        }

        elements.add(position, element)

        if (updateUi)
            notifyItemInserted(position)
        }
    }

    // And so on...

This `updateUi` is dubious anyway, why don't we always notify? Everything with the adapter is supposed to be done on the main thread.

### Expected *expected* behavior

    open fun add(element: T, position: Int = elements.size) {
        checkMainThread()
        elements.add(position, element)
        notifyItemInserted(position)
    }

**Comment by gilgoldzweig** [comment]
You're right, but I'm removing the entire mechanism that checks if it's on the UI thread. 

It's or the system throws an exception or I throw an exception so if that's the case I can remove that logic and clear the code

**Comment by gilgoldzweig** [comment]
I don't see a way to send you a private message but If you'd like to be a contributor I would love some help. 
I'll happily share with you the v3 plans and we can discuss further changes and improvement. 
You're more than welcome to send me a mail.
